# Generated by Django 2.0.2 on 2018-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180218_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=200, null=True, verbose_name='评论所属url'),
        ),
    ]
