# Generated by Django 2.0.2 on 2018-02-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0002_auto_20180213_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
