# Generated by Django 2.0.2 on 2018-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0003_auto_20180213_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='使用markdown格式'),
        ),
    ]
