# Generated by Django 2.0.2 on 2018-02-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0004_post_is_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default='', verbose_name='markdown渲染后的数据'),
        ),
    ]
