# Generated by Django 2.0.2 on 2018-02-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0005_post_content_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=0, verbose_name='pv'),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=0, verbose_name='uv'),
        ),
    ]
