# Generated by Django 2.0.2 on 2018-02-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0006_auto_20180220_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, default='', verbose_name='markdown渲染后的数据'),
        ),
    ]
